apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
  namespace: efklog
  labels:
    k8s-app: fluentd-logging
data:
  fluent.conf: |
    <source>
      @type tail
      path /var/log/containers/*.log
      pos_file /var/log/containers/fluentd-containers.log.pos
      tag kubernetes.*
      format json
      time_key time
      time_format %Y-%m-%dT%H:%M:%S.%N%z
      read_from_head true
      <parse>
        @type multi_format
        <pattern>
          format json
          time_key time
          time_format %Y-%m-%dT%H:%M:%S.%N%z
        </pattern>
        <pattern>
          format regexp
          expression /^(?<time>[^ ]* [^ ]*) (?<stream>[^ ]*) (?<log>.*)$/
          time_format %Y-%m-%dT%H:%M:%S.%N%z
        </pattern>
      </parse>
    </source>

    <filter kubernetes.**>
      @type kubernetes_metadata
    </filter>

    # Filter to include only logs for specific components
    <filter kubernetes.**>
      @type grep
      <regexp>
        key $.kubernetes.container_name
        pattern /(kube-apiserver|kube-scheduler|kube-controller-manager)/
      </regexp>
    </filter>

    <match **>
      @type elasticsearch
      @log_level info
      include_tag_key true
      host elasticsearch-logging.efklog.svc.cluster.local
      port 9200
      logstash_format true
      logstash_prefix kubernetes
      logstash_dateformat %Y.%m.%d
      type_name _doc
      scheme http
      ssl_verify false
      user elastic
      password changeme
      reload_connections true
      reconnect_on_error true
      request_timeout 120s
      time_key @timestamp
      time_key_exclude_timestamp false
      utc_index true
      buffer_chunk_limit 2M
      buffer_queue_limit 8
      flush_interval 5s
      max_retry_wait 30s
      disable_retry_limit false
      retry_wait 1s
      retry_max_interval 30
      num_threads 1
    </match>
